# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for more information:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://containers.dev/guide/dependabot

version: 2
updates:
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: "nuget"
    directory: "/vol_UBP_v1.Plugin"
    schedule:
      interval: "weekly"
    registries:
      - monster-train-packages

registries:
  monster-train-packages:
    type: "nuget-feed"
    url: "https://nuget.pkg.github.com/Monster-Train-2-Modding-Group/index.json"
    username: "${{ secrets.DEPENDABOT_GITHUB_USERNAME }}"
    password: "${{ secrets.DEPENDABOT_GITHUB_TOKEN }}"

