[config]
schemaVersion = "0.0.1"

[package]
namespace = "nik1450"
name = "volcanosunofficialbalance"
versionNumber = "0.0.1"
description = "'a series of changes, intended for c25'"
websiteUrl = "https://thunderstore.io"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
MT2-Trainworks_Reloaded = "0.5.4"
Conductor-Conductor = "0.2.0"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./"

[[build.copy]]
source = "./plugin_build"
target = ""

[publish]
repository = "https://thunderstore.io"
communities = [ "monster-train-2" ]


